/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#faf8ff",
        "surface-bright": "#faf8ff",
        "inverse-on-surface": "#eef0ff",
        "on-primary-container": "#f4fffc",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#002114",
        "tertiary": "#006948",
        "on-secondary-fixed-variant": "#3c475a",
        "surface-container": "#eaedff",
        "surface-variant": "#dae2fd",
        "inverse-surface": "#283044",
        "on-primary": "#ffffff",
        "primary-fixed": "#89f5e7",
        "outline-variant": "#bcc9c6",
        "surface-tint": "#006a61",
        "on-tertiary-container": "#f5fff7",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container-high": "#e2e7ff",
        "secondary-fixed": "#d8e3fb",
        "surface-container-low": "#f2f3ff",
        "primary-container": "#008378",
        "secondary": "#545f73",
        "primary-fixed-dim": "#6bd8cb",
        "secondary-container": "#d5e0f8",
        "tertiary-container": "#00855d",
        "tertiary-fixed": "#85f8c4",
        "on-surface-variant": "#3d4947",
        "on-tertiary-fixed-variant": "#005137",
        "surface-dim": "#d2d9f4",
        "primary": "#00685f",
        "on-secondary-fixed": "#111c2d",
        "on-error": "#ffffff",
        "inverse-primary": "#6bd8cb",
        "secondary-fixed-dim": "#bcc7de",
        "on-surface": "#131b2e",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface": "#faf8ff",
        "on-secondary-container": "#586377",
        "outline": "#6d7a77",
        "surface-container-highest": "#dae2fd",
        "error": "#ba1a1a",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#005049",
        "on-background": "#131b2e",
        "tertiary-fixed-dim": "#68dba9"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1rem",
        "margin": "2rem",
        "space-md": "1rem",
        "space-lg": "1.5rem"
      },
      fontFamily: {
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", letterSpacing: "0.005em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "22px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
};
